[tool.poetry]
name = "rl-sr-validation"
version = "0.1.0"
description = ""
authors = ["Charlotte Kostelic <charlottekostelic@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.5.3"
pymarc = "^5.1.0"
pytest = "^7.4.3"
rich = "^13.7.0"
click = "^8.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]